// <auto-generated />
using System;
using ASIB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASIB.Migrations
{
    [DbContext(typeof(AsibContext))]
    partial class AsibContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ASIB.Models.Action", b =>
                {
                    b.Property<long>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("action_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ActionId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("action_type");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("EntityId")
                        .HasColumnType("int(11)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.HasKey("ActionId")
                        .HasName("PRIMARY");

                    b.ToTable("action", (string)null);
                });

            modelBuilder.Entity("ASIB.Models.Admin", b =>
                {
                    b.Property<long>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("admin_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AdminId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("AdminId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("ASIB.Models.AdminAction", b =>
                {
                    b.Property<long>("AdminActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("admin_action_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AdminActionId"));

                    b.Property<DateTime>("ActionTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("action_time")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("action_type");

                    b.Property<long>("AdminId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("admin_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<long?>("TargetEventId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("target_event_id");

                    b.Property<long?>("TargetPostId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("target_post_id");

                    b.Property<long?>("TargetUserId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("target_user_id");

                    b.HasKey("AdminActionId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AdminId" }, "fk_admin_actions_admin");

                    b.ToTable("admin_actions", (string)null);
                });

            modelBuilder.Entity("ASIB.Models.Announcement", b =>
                {
                    b.Property<long>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("announcement_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AnnouncementId"));

                    b.Property<long>("AdminId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("admin_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("current_timestamp()");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("AnnouncementId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AdminId" }, "fk_announcements_admin");

                    b.ToTable("announcements", (string)null);
                });

            modelBuilder.Entity("ASIB.Models.Connection", b =>
                {
                    b.Property<long>("ConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("connection_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ConnectionId"));

                    b.Property<long>("AddresseeId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("addressee_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<long>("RequesterId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("requester_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pending','accepted','declined','blocked')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("current_timestamp()");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("ConnectionId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AddresseeId" }, "fk_connections_addressee");

                    b.HasIndex(new[] { "RequesterId", "AddresseeId" }, "unique_connection")
                        .IsUnique();

                    b.ToTable("connections", (string)null);
                });

            modelBuilder.Entity("ASIB.Models.Embedding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Embedding1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("embedding");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("embeddings", (string)null);
                });

            modelBuilder.Entity("ASIB.Models.Engagement", b =>
                {
                    b.Property<long>("EngagementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("engagement_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("EngagementId"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content")
                        .HasComment("Used for comments");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("EngagementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("engagement_type")
                        .HasComment("e.g., 'like', 'comment'");

                    b.Property<long?>("PostId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("post_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("user_id");

                    b.HasKey("EngagementId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "fk_engagements_user");

                    b.HasIndex(new[] { "PostId", "UserId", "EngagementType" }, "post_user_type_idx");

                    b.ToTable("engagements", (string)null);
                });

            modelBuilder.Entity("ASIB.Models.Event", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("event_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("EventId"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("end_time");

                    b.Property<string>("MeetingUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("meeting_url");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("start_time")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("user_id");

                    b.HasKey("EventId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CreatedBy" }, "fk_events_created_by");

                    b.HasIndex(new[] { "RoleId" }, "fk_events_role");

                    b.HasIndex(new[] { "UserId" }, "fk_events_user");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("ASIB.Models.EventRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("request_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<long>("EventId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pending','approved','declined')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("user_id");

                    b.HasKey("RequestId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EventId", "UserId" }, "event_user_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "fk_eventrequests_user");

                    b.ToTable("event_requests", (string)null);
                });

            modelBuilder.Entity("ASIB.Models.Follow", b =>
                {
                    b.Property<long>("FollowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("follow_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("FollowId"));

                    b.Property<DateTime>("FollowedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("followed_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<long?>("FollowerId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("follower_id");

                    b.Property<long?>("FollowingId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("following_id");

                    b.HasKey("FollowId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FollowingId" }, "fk_follows_following");

                    b.HasIndex(new[] { "FollowerId", "FollowingId" }, "unique_follow")
                        .IsUnique();

                    b.ToTable("follows", (string)null);
                });

            modelBuilder.Entity("ASIB.Models.Message", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("message_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("MessageId"));

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("attachment_path");

                    b.Property<string>("AttachmentType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("attachment_type");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<bool?>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("deleted")
                        .HasDefaultValueSql("'10'");

                    b.Property<long?>("ReceiverId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("receiver_id");

                    b.Property<long?>("SenderId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("sender_id");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("MessageId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ReceiverId" }, "fk_messages_receiver");

                    b.HasIndex(new[] { "SenderId" }, "fk_messages_sender");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("ASIB.Models.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("notification_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("entity_id")
                        .HasComment("ID of the related item (post_id, sender_id, etc.)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<long>("ReceiverId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("receiver_id");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("sender_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("enum('like','comment','follow','connect_request','connect_accept','new_post','message')")
                        .HasColumnName("type");

                    b.HasKey("NotificationId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ReceiverId" }, "fk_notifications_receiver");

                    b.HasIndex(new[] { "SenderId" }, "fk_notifications_sender");

                    b.HasIndex(new[] { "ReceiverId", "IsRead" }, "idx_receiver_read");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("ASIB.Models.PasswordReset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("otp_hash");

                    b.Property<bool>("Used")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("used");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "idx_user");

                    b.ToTable("password_resets", (string)null);
                });

            modelBuilder.Entity("ASIB.Models.Post", b =>
                {
                    b.Property<long>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("post_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("PostId"));

                    b.Property<int>("CommentsCount")
                        .HasColumnType("int(11)")
                        .HasColumnName("comments_count");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int>("LikesCount")
                        .HasColumnType("int(11)")
                        .HasColumnName("likes_count");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("photo_url");

                    b.Property<string>("PostType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("post_type")
                        .HasDefaultValueSql("'general'");

                    b.Property<int>("SharesCount")
                        .HasColumnType("int(11)")
                        .HasColumnName("shares_count");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("user_id");

                    b.HasKey("PostId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "fk_posts_user");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("ASIB.Models.Profile", b =>
                {
                    b.Property<long>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("profile_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ProfileId"));

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("Experience")
                        .HasColumnType("text")
                        .HasColumnName("experience");

                    b.Property<string>("Headline")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("headline");

                    b.Property<bool?>("PrivacySetting")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("privacy_setting")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("profile_photo_url");

                    b.Property<string>("Skills")
                        .HasColumnType("text")
                        .HasColumnName("skills");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("user_id");

                    b.HasKey("ProfileId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "fk_profiles_user");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("ASIB.Models.Report", b =>
                {
                    b.Property<long>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("report_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ReportId"));

                    b.Property<long>("PostId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("post_id");

                    b.Property<string>("Reason")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reason")
                        .HasDefaultValueSql("'No reason provided.'");

                    b.Property<DateTime>("ReportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("reported_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<long>("ReporterId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("reporter_id");

                    b.HasKey("ReportId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ReporterId" }, "reporter_id");

                    b.HasIndex(new[] { "PostId", "ReporterId" }, "unique_report")
                        .IsUnique();

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("ASIB.Models.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("role_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("RoleId"));

                    b.Property<string>("Role1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("role");

                    b.HasKey("RoleId")
                        .HasName("PRIMARY");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("ASIB.Models.Share", b =>
                {
                    b.Property<long>("ShareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("share_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ShareId"));

                    b.Property<long>("PostId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("post_id");

                    b.Property<DateTime>("SharedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("shared_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("user_id");

                    b.HasKey("ShareId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PostId", "UserId" }, "post_id")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "user_id");

                    b.ToTable("shares", (string)null);
                });

            modelBuilder.Entity("ASIB.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<int?>("BatchYear")
                        .HasColumnType("int(11)")
                        .HasColumnName("batch_year");

                    b.Property<long>("ContactNumber")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("contact_number");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("EnrollmentNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("enrollment_number");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<bool?>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_online")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_seen");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("role_id");

                    b.Property<long?>("RoleRequested")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("role_requested");

                    b.Property<int?>("VerificationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("verification_status")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique()
                        .HasDatabaseName("email1");

                    b.HasIndex(new[] { "RoleId" }, "fk_users_role");

                    b.HasIndex(new[] { "RoleRequested" }, "fk_users_role_requested");

                    b.HasIndex(new[] { "EnrollmentNumber" }, "idx_enrollment_unique")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ASIB.Models.ViewModels.AdminPromotedAlumniRow", b =>
                {
                    b.Property<int?>("BatchYear")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PromotedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.ToTable("AdminPromotedAlumniRows");
                });

            modelBuilder.Entity("ASIB.Models.ViewModels.MyNetworkSuggestionRow", b =>
                {
                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Headline")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.ToTable("MyNetworkSuggestionRows");
                });

            modelBuilder.Entity("ASIB.Models.ViewModels.ViewPostRow", b =>
                {
                    b.Property<int>("CommentsCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedAtText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IsFollowing")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LikesCount")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("longtext");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<string>("PostType")
                        .HasColumnType("longtext");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("SharesCount")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.ToTable("ViewPostRows");
                });

            modelBuilder.Entity("ASIB.Models.AdminAction", b =>
                {
                    b.HasOne("ASIB.Models.Admin", "Admin")
                        .WithMany("AdminActions")
                        .HasForeignKey("AdminId")
                        .IsRequired()
                        .HasConstraintName("admin_actions_ibfk_1");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("ASIB.Models.Announcement", b =>
                {
                    b.HasOne("ASIB.Models.Admin", "Admin")
                        .WithMany("Announcements")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_announcements_admin");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("ASIB.Models.Admin", b =>
                {
                    b.Navigation("AdminActions");

                    b.Navigation("Announcements");
                });
#pragma warning restore 612, 618
        }
    }
}
